# ============================================================
# FOLD CONSISTENCY ANALYSIS
#
# Uses SHAP importance generated by:
#     shap_analysis_final.py
# ============================================================

import os
import pandas as pd
import matplotlib.pyplot as plt


# ============================================================
# PATHS
# ============================================================

INPUT = (
    "outputs/shap/"
    "fold_feature_importance.csv"
)

OUT_DIR = "outputs/shap"

os.makedirs(
    OUT_DIR,
    exist_ok=True
)


# ============================================================
# LOAD
# ============================================================

importance = pd.read_csv(
    INPUT,
    index_col=0
)

print("=" * 70)

print(
    "FOLD CONSISTENCY ANALYSIS"
)

print("=" * 70)

print(
    "\nLoaded:",
    importance.shape
)


# ============================================================
# TOP 5 PER FOLD
# ============================================================

fold_top5 = {}

for fold in importance.index:

    top5 = (
        importance.loc[fold]
        .sort_values(
            ascending=False
        )
        .head(5)
        .index
        .tolist()
    )

    fold_top5[fold] = top5

    print(
        f"\n{fold}:"
    )

    for rank, feature in enumerate(
        top5,
        start=1
    ):

        print(
            f"  {rank}. {feature}"
        )


# ============================================================
# COUNT APPEARANCES
# ============================================================

counts = {}

for fold, features in fold_top5.items():

    for feature in features:

        counts[feature] = (
            counts.get(feature, 0) + 1
        )


consistency = (
    pd.DataFrame(
        {
            "feature":
                list(counts.keys()),

            "top5_fold_count":
                list(counts.values())
        }
    )
    .sort_values(
        [
            "top5_fold_count",
            "feature"
        ],
        ascending=[
            False,
            True
        ]
    )
)


# ============================================================
# SAVE
# ============================================================

consistency.to_csv(
    os.path.join(
        OUT_DIR,
        "fold_consistency.csv"
    ),
    index=False
)


# ============================================================
# TOP 5 CONSISTENCY
# ============================================================

top_consistent = (
    consistency
    .head(15)
    .sort_values(
        "top5_fold_count"
    )
)


plt.figure(
    figsize=(9, 7)
)

plt.barh(
    top_consistent["feature"],
    top_consistent["top5_fold_count"]
)

plt.xlabel(
    "Number of folds appearing in Top 5"
)

plt.ylabel(
    "Feature"
)

plt.title(
    "Feature Importance Consistency Across 5 Folds"
)

plt.xlim(
    0,
    5.5
)

plt.tight_layout()

plt.savefig(
    os.path.join(
        OUT_DIR,
        "fold_consistency.png"
    ),
    dpi=300,
    bbox_inches="tight"
)

plt.close()


# ============================================================
# STABILITY TABLE
# ============================================================

stability = consistency.copy()

stability["consistency_percent"] = (
    stability["top5_fold_count"]
    / 5
    * 100
)

stability.to_csv(
    os.path.join(
        OUT_DIR,
        "feature_stability.csv"
    ),
    index=False
)


# ============================================================
# FINAL
# ============================================================

print("\n")
print("=" * 70)

print(
    "FEATURE CONSISTENCY"
)

print("=" * 70)

print(
    consistency.to_string(
        index=False
    )
)

print("\n")
print(
    "Saved:"
)

print(
    os.path.join(
        OUT_DIR,
        "fold_consistency.csv"
    )
)

print(
    os.path.join(
        OUT_DIR,
        "fold_consistency.png"
    )
)

print(
    os.path.join(
        OUT_DIR,
        "feature_stability.csv"
    )
)